### ISSUE TITLE
Cannot query by viewer without public schema active

### ISSUE THREAD

**Issue by J-Protz** [jamesedmonston/graphql-authentication#66] opened 2021-08-10 17:40 UTC
When trying to query information using the auth JWT,  I get an error saying Authorization header is missing if the public schema is disabled. If enabled, even with all options unchecked, it then works.

**Comment by jamesedmonston** [comment] 2021-08-14 10:21
Duplicate of https://github.com/jamesedmonston/graphql-authentication/issues/52

**Closed by jamesedmonston** 2021-08-14 10:21 UTC
